package com.revenuecat.purchases.utils;

/* JADX INFO: loaded from: classes4.dex */
@kotlin.Metadata(d1 = {"\u0000&\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\bÀ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0017\u0010\u0007\u001a\u00020\u00022\u0006\u0010\u0006\u001a\u00020\u0005H\u0016¢\u0006\u0004\b\u0007\u0010\bJ#\u0010\f\u001a\u00020\u000b*\u00020\u00022\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\n\u001a\u00020\tH\u0016¢\u0006\u0004\b\f\u0010\r¨\u0006\u000e"}, d2 = {"Lcom/revenuecat/purchases/utils/JSONObjectParceler;", "", "Lorg/json/JSONObject;", "<init>", "()V", "Landroid/os/Parcel;", "parcel", "create", "(Landroid/os/Parcel;)Lorg/json/JSONObject;", "", "flags", "Lh6/A;", "write", "(Lorg/json/JSONObject;Landroid/os/Parcel;I)V", "purchases_defaultsRelease"}, k = 1, mv = {1, 8, 0}, xi = androidx.media3.container.NalUnitUtil.H265_NAL_UNIT_TYPE_UNSPECIFIED)
public final class JSONObjectParceler {
    public static final com.revenuecat.purchases.utils.JSONObjectParceler INSTANCE = new com.revenuecat.purchases.utils.JSONObjectParceler();

    private JSONObjectParceler() {
    }

    public org.json.JSONObject create(android.os.Parcel parcel) {
        kotlin.jvm.internal.m.e(parcel, "parcel");
        return new org.json.JSONObject(parcel.readString());
    }

    public org.json.JSONObject[] newArray(int i3) {
        throw new p070h6.j("Generated by Android Extensions automatically");
    }

    public void write(org.json.JSONObject jSONObject, android.os.Parcel parcel, int i3) {
        kotlin.jvm.internal.m.e(jSONObject, "<this>");
        kotlin.jvm.internal.m.e(parcel, "parcel");
        parcel.writeString(jSONObject.toString());
    }
}
