package p052f5;

import com.kiptv.tv.R;
import p070h6.k;
import p078i6.C;

public abstract class c {

    public static final Object f21715a = C.N0(new k("ic_rating_au_g", Integer.valueOf(R.drawable.ic_rating_au_g)), new k("ic_rating_au_m", Integer.valueOf(R.drawable.ic_rating_au_m)), new k("ic_rating_au_ma_15plus", Integer.valueOf(R.drawable.ic_rating_au_ma_15plus)), new k("ic_rating_au_pg", Integer.valueOf(R.drawable.ic_rating_au_pg)), new k("ic_rating_au_r_18plus", Integer.valueOf(R.drawable.ic_rating_au_r_18plus)), new k("ic_rating_au_x_18plus", Integer.valueOf(R.drawable.ic_rating_au_x_18plus)), new k("ic_rating_br_10", Integer.valueOf(R.drawable.ic_rating_br_10)), new k("ic_rating_br_12", Integer.valueOf(R.drawable.ic_rating_br_12)), new k("ic_rating_br_14", Integer.valueOf(R.drawable.ic_rating_br_14)), new k("ic_rating_br_16", Integer.valueOf(R.drawable.ic_rating_br_16)), new k("ic_rating_br_18", Integer.valueOf(R.drawable.ic_rating_br_18)), new k("ic_rating_br_l", Integer.valueOf(R.drawable.ic_rating_br_l)), new k("ic_rating_de_0", Integer.valueOf(R.drawable.ic_rating_de_0)), new k("ic_rating_de_12", Integer.valueOf(R.drawable.ic_rating_de_12)), new k("ic_rating_de_16", Integer.valueOf(R.drawable.ic_rating_de_16)), new k("ic_rating_de_18", Integer.valueOf(R.drawable.ic_rating_de_18)), new k("ic_rating_de_6", Integer.valueOf(R.drawable.ic_rating_de_6)), new k("ic_rating_ie_12", Integer.valueOf(R.drawable.ic_rating_ie_12)), new k("ic_rating_ie_12a", Integer.valueOf(R.drawable.ic_rating_ie_12a)), new k("ic_rating_ie_15", Integer.valueOf(R.drawable.ic_rating_ie_15)), new k("ic_rating_ie_15a", Integer.valueOf(R.drawable.ic_rating_ie_15a)), new k("ic_rating_ie_16", Integer.valueOf(R.drawable.ic_rating_ie_16)), new k("ic_rating_ie_18", Integer.valueOf(R.drawable.ic_rating_ie_18)), new k("ic_rating_ie_g", Integer.valueOf(R.drawable.ic_rating_ie_g)), new k("ic_rating_ie_pg", Integer.valueOf(R.drawable.ic_rating_ie_pg)), new k("ic_rating_it_10plus", Integer.valueOf(R.drawable.ic_rating_it_10plus)), new k("ic_rating_it_14plus", Integer.valueOf(R.drawable.ic_rating_it_14plus)), new k("ic_rating_it_18plus", Integer.valueOf(R.drawable.ic_rating_it_18plus)), new k("ic_rating_it_6plus", Integer.valueOf(R.drawable.ic_rating_it_6plus)), new k("ic_rating_it_t", Integer.valueOf(R.drawable.ic_rating_it_t)), new k("ic_rating_us_tv_tv_14", Integer.valueOf(R.drawable.ic_rating_us_tv_tv_14)), new k("ic_rating_us_tv_tv_g", Integer.valueOf(R.drawable.ic_rating_us_tv_tv_g)), new k("ic_rating_us_tv_tv_ma", Integer.valueOf(R.drawable.ic_rating_us_tv_tv_ma)), new k("ic_rating_us_tv_tv_pg", Integer.valueOf(R.drawable.ic_rating_us_tv_tv_pg)), new k("ic_rating_us_tv_tv_y", Integer.valueOf(R.drawable.ic_rating_us_tv_tv_y)), new k("ic_rating_us_tv_tv_y7", Integer.valueOf(R.drawable.ic_rating_us_tv_tv_y7)));
}
